"""Added image_url to users

Revision ID: de6109809aa7
Revises: 6ec1b2ccb082
Create Date: 2024-03-22 02:47:17.186937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de6109809aa7'
down_revision = '6ec1b2ccb082'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Since SQLite does not support altering columns directly, 
    # the command to alter 'product_id' to nullable=True is removed for SQLite compatibility.
    op.add_column('users', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_url')
    # No direct downgrade operation for 'product_id' column alteration due to SQLite's limitations.
    # If you need to revert this in SQLite, consider manual intervention or a more complex migration strategy.
    # ### end Alembic commands ###
